language: ruby
rvm:
  - 2.1
install: gem install jekyll html-proofer
script:
  - bundle install
  - jekyll build
  - bundle exec htmlproofer ./_site --only-4xx --check-favicon --check-html
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer