# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Anton Sizikov
url:              https://asizikov.github.io
tagline:          'Anton Sizikov'
description:      ".NET Software Engineer's blog."
baseurl:          ""

twitter:
  username: return_true
github:
  username: asizikov
  repo: https://github.com/asizikov
social:
  type: person
  name: Anton Sizikov
  links:
    twitter: https://www.twitter.com/return_true
    github: https://github.com/asizikov


paginate:         5

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Custom vars
version:          2.1.0

gems:             [jekyll-paginate, jekyll-gist, rouge, jekyll-seo-tag]
