# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Anton Sizikov
url:              http://asizikov.github.io/
tagline:          'Anton Sizikov'
description:      ".NET Software Engineer's blog."
baseurl:          /

author:
  name:           'Anton Sizikov'
  url:            https://twitter.com/return_true

twitter:
   username: return_true

paginate:         5

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/asizikov
gems:             [jekyll-paginate, jekyll-gist, rouge, jekyll-seo-tag]
