version: '3'  
services: 
  hugo: 
    image: klakegg/hugo:latest  
    ports:  
      - "4000:4000" 
    volumes:  
      - ./:/src
    command: server
    tty: true 
    ports:
      - "1313:1313"