name = "Okayish Blog Hugo Theme"
license = "MIT"
licenselink = "https://github.com/kongdivin/hugo-theme-okayish-blog/blob/master/LICENSE"
description = "An ok-ish blog theme based on Vanilla"
homepage = "https://github.com/kongdivin/hugo-theme-okayish-blog#readme"
tags = ["blog", "responsive", "i18n"]
features = [
  "responsive",  
  "google analytics",
  "disqus comments",
  "share links",
  "google site search",
  "i18n",
  "seo",
  "accessibility"
]
min_version = "0.62.2"

[author]
  name = "Divin Kong"
  homepage = "https://twitter.com/kongdivin"